name: Manual Deploy to Production

on:
  workflow_dispatch:  # Ez engedélyezi a "Run workflow" gombot

jobs:
  deploy:
    name: Deploy over SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/tarsasapp
            git pull origin main
            docker compose down
            docker compose up -d --build
